=== KoiRealm/Fuke/source/Fuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/KoiRealm/Fuke/main/source/Fuke.Tooling.Generator/schema.json",
  "title": "Tool specification schema file by FUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "hidesBaseMember": {
          "description": "Specifies that the property hides an inherited member and requires the new modifier.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/DotnetPackaging/DotnetPackaging.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/main/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://github.com/SuperJMN/DotnetPackaging/tree/master/src/DotnetPackaging.Console"
  ],
  "name": "DotnetPackaging",
  "officialUrl": "https://github.com/superjmn/dotnetpackaging",
  "help": "DotnetPackaging is able to package your application into various formats, including Deb and AppImage.",
  "nugetPackageId": "DotnetPackaging.Console",
  "packageExecutable": "DotnetPackaging.Console.dll",
  "tasks": [
    {
      "help": "Creates a Debian package from the specified directory.",
      "postfix": "Deb",
      "definiteArgument": "deb",
      "settingsClass": {
        "properties": [
          {
            "name": "Directory",
            "type": "string",
            "format": "--directory={value}",
            "help": "The input directory from which to create the package."
          },
          {
            "name": "Metadata",
            "type": "string",
            "format": "--metadata={value}",
            "help": "The metadata file to include in the package."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--output={value}",
            "help": "The output DEB file to create."
          }
        ]
      }
    },
    {
      "help": "Creates an AppImage package.",
      "postfix": "AppImage",
      "definiteArgument": "appimage",
      "settingsClass": {
        "properties": [
          {
            "name": "Directory",
            "type": "string",
            "format": "--directory={value}",
            "help": "The input directory from which to create the AppImage."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--output={value}",
            "help": "The output AppImage file to create."
          },
          {
            "name": "ApplicationName",
            "type": "string",
            "format": "--application-name={value}",
            "help": "The name of the application for the AppImage."
          },
          {
            "name": "MainCategory",
            "type": "DotnetPackagingMainCategory",
            "format": "--main-category {value}",
            "help": "Main category of the application."
          },
          {
            "name": "AdditionalCategories",
            "type": "List<DotnetPackagingAdditionalCategory>",
            "format": "--additional-categories {value}",
            "help": "Additional categories for the application."
          },
          {
            "name": "Icon",
            "type": "string",
            "format": "--icon {value}",
            "help": "The icon path for the application. When not provided, the tool looks up for an image called <c>AppImage.png</c>."
          },
          {
            "name": "Homepage",
            "type": "string",
            "format": "--homepage {value}",
            "help": "Home page of the application."
          },
          {
            "name": "License",
            "type": "string",
            "format": "--license {value}",
            "help": "License of the application."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--version {value}",
            "help": "Version of the application."
          },
          {
            "name": "ScreenshotUrls",
            "type": "List<string>",
            "format": "--screenshot-urls {value}",
            "help": "URLs of screenshots of the application."
          },
          {
            "name": "Summary",
            "type": "string",
            "format": "--summary {value}",
            "help": "Short description of the application."
          },
          {
            "name": "AppId",
            "type": "string",
            "format": "--appId {value}",
            "help": "Application ID, usually a reverse DNS name like <c>com.SomeCompany.SomeApplication</c>."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "DotnetPackagingMainCategory",
      "values": [
        "AudioVideo",
        "Audio",
        "Video",
        "Development",
        "Education",
        "Game",
        "Graphics",
        "Network",
        "Office",
        "Settings",
        "Utility"
      ]
    },
    {
      "name": "DotnetPackagingAdditionalCategory",
      "values": [
        "Building",
        "Debugger",
        "IDE",
        "GUIDesigner",
        "Profiling",
        "RevisionControl",
        "Translation",
        "Calendar",
        "ContactManagement",
        "Database",
        "Dictionary",
        "Chart",
        "Email",
        "Finance",
        "FlowChart",
        "PDA",
        "ProjectManagement",
        "Presentation",
        "Spreadsheet",
        "WordProcessor",
        "TwoDGraphics",
        "VectorGraphics",
        "RasterGraphics",
        "ThreeDGraphics",
        "Scanning",
        "OCR",
        "Photography",
        "Publishing",
        "Viewer",
        "TextTools",
        "DesktopSettings",
        "HardwareSettings",
        "Printing",
        "PackageManager",
        "Dialup",
        "InstantMessaging",
        "Chat",
        "IRCClient",
        "FileTransfer",
        "HamRadio",
        "News",
        "P2P",
        "RemoteAccess",
        "Telephony",
        "TelephonyTools",
        "VideoConference",
        "WebBrowser",
        "WebDevelopment",
        "Midi",
        "Mixer",
        "Sequencer",
        "Tuner",
        "TV",
        "AudioVideoEditing",
        "Player",
        "Recorder",
        "DiscBurning",
        "ActionGame",
        "AdventureGame",
        "ArcadeGame",
        "BoardGame",
        "BlocksGame",
        "CardGame",
        "KidsGame",
        "LogicGame",
        "RolePlaying",
        "Simulation",
        "SportsGame",
        "StrategyGame",
        "Art",
        "Construction",
        "Music",
        "Languages",
        "Science",
        "ArtificialIntelligence",
        "Astronomy",
        "Biology",
        "Chemistry",
        "ComputerScience",
        "DataVisualization",
        "Economy",
        "Electricity",
        "Geography",
        "Geology",
        "Geoscience",
        "History",
        "ImageProcessing",
        "Literature",
        "Math",
        "NumericalAnalysis",
        "MedicalSoftware",
        "Physics",
        "Robotics",
        "Sports",
        "ParallelComputing",
        "Amusement",
        "Archiving",
        "Compression",
        "Electronics",
        "Emulator",
        "Engineering",
        "FileTools",
        "FileManager",
        "TerminalEmulator",
        "Filesystem",
        "Monitor",
        "Security",
        "Accessibility",
        "Calculator",
        "Clock",
        "TextEditor",
        "Documentation",
        "Core",
        "KDE",
        "GNOME",
        "GTK",
        "Qt",
        "Motif",
        "Java",
        "ConsoleOnly"
      ]
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/Codecov/Codecov.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/main/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://raw.githubusercontent.com/codecov/codecov-exe/master/Source/Codecov/Program/CommandLineOptions.cs"
  ],
  "name": "Codecov",
  "officialUrl": "https://about.codecov.io/",
  "help": "Code coverage is a measurement used to express which lines of code were executed by a test suite. We use three primary terms to describe each line executed.<para/><ul><li>hit - indicates that the source code was executed by the test suite.</li><li>partial - indicates that the source code was not fully executed by the test suite; there are remaining branches that were not executed.</li><li>miss - indicates that the source code was not executed by the test suite.</li></ul><para/>Coverage is the ratio of <c>hits / (sum of hit + partial + miss)</c>. A code base that has 5 lines executed by tests out of 12 total lines will receive a coverage ratio of 41% (rounding down).<para/>Phrased simply, code coverage provides a visual measurement of what source code is being executed by a test suite. This information indicates to the software developer where they should write new tests in an effort to achieve higher coverage.<para/>Testing source code helps to prevent bugs and syntax errors by executing each line with a known variable and cross-checking it with an expected output.",
  "nugetPackageId": "CodecovUploader",
  "customExecutable": true,
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "Branch",
            "type": "string",
            "format": "--branch {value}",
            "help": "Specify the branch name."
          },
          {
            "name": "Build",
            "type": "string",
            "format": "--build {value}",
            "help": "Specify the build number."
          },
          {
            "name": "Sha",
            "type": "string",
            "format": "--sha {value}",
            "help": "Specify the commit sha."
          },
          {
            "name": "DisableNetwork",
            "type": "bool",
            "format": "--disable-network",
            "help": "Disable uploading the file network."
          },
          {
            "name": "Dump",
            "type": "bool",
            "format": "--dump",
            "help": "Don't upload and dump to stdin."
          },
          {
            "name": "EnvironmentVariables",
            "type": "List<string>",
            "format": "--env {value}",
            "separator": " ",
            "help": "Specify environment variables to be included with this build."
          },
          {
            "name": "Features",
            "type": "List<string>",
            "format": "--feature {value}",
            "help": "Specify features to disable."
          },
          {
            "name": "Files",
            "type": "List<string>",
            "format": "--file {value}",
            "separator": " ",
            "help": "Target file(s) to upload."
          },
          {
            "name": "Flags",
            "type": "string",
            "format": "--flag {value}",
            "separator": ",",
            "help": "Flag the upload to group coverage metrics."
          },
          {
            "name": "Name",
            "type": "string",
            "format": "--name {value}",
            "help": "Custom defined name of the upload. Visible in Codecov UI."
          },
          {
            "name": "NoColor",
            "type": "bool",
            "format": "--no-color",
            "help": "Remove color from the output."
          },
          {
            "name": "PullRequest",
            "type": "string",
            "format": "--pr {value}",
            "help": "Specify the pull request number."
          },
          {
            "name": "RepositoryRoot",
            "type": "string",
            "format": "--root {value}",
            "help": "Used when not in git/hg project to identify project root directory."
          },
          {
            "name": "Required",
            "type": "bool",
            "format": "--required",
            "help": "Exit with <c>1</c> if not successful. Default will Exit with <c>0</c>."
          },
          {
            "name": "Slug",
            "type": "string",
            "format": "--slug {value}",
            "help": "Owner/repo slug used instead of the private repo token in Enterprise."
          },
          {
            "name": "Tag",
            "type": "string",
            "format": "--tag {value}",
            "help": "Specify the git tag."
          },
          {
            "name": "Token",
            "type": "string",
            "format": "--token {value}",
            "secret": true,
            "help": "Set the private repository token."
          },
          {
            "name": "Url",
            "type": "string",
            "format": "--url {value}",
            "help": "Set the target url for Enterprise customers."
          },
          {
            "name": "Verbose",
            "type": "bool",
            "format": "--verbose",
            "help": "Verbose mode."
          },
          {
            "name": "Framework",
            "type": "string",
            "noArgument": true
          }
        ]
      }
    }
  ]
}
