=== KoiRealm/Fuke/source/Fuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/KoiRealm/Fuke/main/source/Fuke.Tooling.Generator/schema.json",
  "title": "Tool specification schema file by FUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "hidesBaseMember": {
          "description": "Specifies that the property hides an inherited member and requires the new modifier.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/TestCloud/TestCloud.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/master/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://developer.xamarin.com/guides/testcloud/uitest/working-with/submitting-tests-at-command-line#//div[@class='doc-content']/table"
  ],
  "name": "TestCloud",
  "officialUrl": "https://developer.xamarin.com/guides/testcloud/",
  "help": "Test Cloud is a cloud based service consisting of thousands of physical mobile devices. Users upload their apps and tests to Test Cloud, which will install the apps on the devices and run the tests. When the tests are complete, Test Cloud, the results made available to users through an easy to use and informative web-based front end.",
  "nugetPackageId": "Xamarin.UITest",
  "packageExecutable": "test-cloud.exe",
  "tasks": [
    {
      "definiteArgument": "submit",
      "settingsClass": {
        "properties": [
          {
            "name": "AssemblyDirectory",
            "type": "string",
            "format": "--assembly-dir {value}",
            "help": "The path to the folder holding the test assemblies."
          },
          {
            "name": "Devices",
            "type": "string",
            "format": "--devices {value}",
            "help": "The device ID that was provided in the Test Cloud Upload dialog."
          },
          {
            "name": "UserEmail",
            "type": "string",
            "format": "--user {value}",
            "help": "The e-mail address of the team member submitting the tests."
          },
          {
            "name": "NunitResultsFile",
            "type": "string",
            "format": "--nunit-xml {value}",
            "help": "The filename to which test results are exported, formatted as NUnit results XML. Optional."
          },
          {
            "name": "SignInfoFile",
            "type": "string",
            "format": "--sign-info {value}",
            "help": "Android only. Supply a signing information file that will be used to sign the Test Server APK. See the section below for more details. Optional."
          },
          {
            "name": "DsymFile",
            "type": "string",
            "format": "--dsym {value}",
            "help": "iOS only. Will upload the dSYM files along with the application and tests. This allows for more detail in the log files. Optional."
          },
          {
            "name": "Fixtures",
            "type": "List<string>",
            "format": "--fixture {value}",
            "help": "NUnit fixture / namespace to run. (Can be used multiple times)."
          },
          {
            "name": "IncludeCategories",
            "type": "List<string>",
            "format": "--include {value}",
            "help": "Identifies the NUnit test categories that should only be included in the test run."
          },
          {
            "name": "ExcludeCategories",
            "type": "List<string>",
            "format": "--exclude {value}",
            "help": "Identifies the NUnit test categories that should be excluded from the test run."
          },
          {
            "name": "TestChunk",
            "type": "bool",
            "format": "--test-chunk",
            "help": "Run tests in parallel by method."
          },
          {
            "name": "FixtureChunk",
            "type": "bool",
            "format": "--fixture-chunk",
            "help": "Run tests in parallel by fixture."
          },
          {
            "name": "DataPaths",
            "type": "List<string>",
            "format": "--data {value}",
            "help": "Uploads file or directory along with assemblies. (Can be used multiple times)."
          }
        ]
      }
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/Mastodon/Mastodon.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/main/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://discord.com/developers/docs/resources/channel#create-message"
  ],
  "name": "Mastodon",
  "officialUrl": "https://docs.joinmastodon.org/",
  "dataClasses": [
    {
      "name": "MastodonStatus",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Text",
          "type": "string",
          "help": "Text of the status."
        },
        {
          "name": "MediaFiles",
          "type": "List<string>",
          "help": "Media files to attach to the status."
        }
      ]
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/Discord/Discord.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/master/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://discord.com/developers/docs/resources/channel#create-message"
  ],
  "name": "Discord",
  "officialUrl": "https://discord.com/developers/docs/intro",
  "dataClasses": [
    {
      "name": "DiscordMessage",
      "extensionMethods": true,
      "properties": [
        {
          "name": "ChannelId",
          "type": "string",
          "json": "channel_id",
          "help": "Id of the channel."
        },
        {
          "name": "Content",
          "type": "string",
          "json": "content",
          "help": "Message contents (up to 2000 characters)."
        },
        {
          "name": "Nonce",
          "type": "string",
          "json": "nonce",
          "help": "Can be used to verify a message was sent (up to 25 characters). Value will appear in the <a href=\"https://discord.com/developers/docs/topics/gateway-events#message-create\">Message Create event</a>."
        },
        {
          "name": "TTS",
          "type": "bool",
          "json": "tts",
          "help": "Whether this is a TTS message."
        },
        {
          "name": "Embeds",
          "type": "List<DiscordEmbed>",
          "json": "embeds",
          "help": "Embedded rich content (up to 6000 characters). See <a href=\"https://autocode.com/tools/discord/embed-builder/\">Discord Embed Builder</a>."
        }
      ]
    },
    {
      "name": "DiscordEmbed",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Title",
          "type": "string",
          "json": "title",
          "help": "Title of embed."
        },
        {
          "name": "Type",
          "type": "DiscordEmbedType",
          "json": "type",
          "help": "<a href=\"https://discord.com/developers/docs/resources/channel#embed-object-embed-types\">Type of embed</a> (always <c>rich</c> for webhook embeds)."
        },
        {
          "name": "Description",
          "type": "string",
          "json": "description",
          "help": "Description of embed."
        },
        {
          "name": "Url",
          "type": "string",
          "json": "url",
          "help": "Url of embed."
        },
        {
          "name": "Timestamp",
          "type": "string",
          "json": "timestamp",
          "help": "ISO8601 timestamp of embed."
        },
        {
          "name": "Color",
          "type": "int",
          "json": "color",
          "help": "Color code of the embed."
        },
        {
          "name": "Footer",
          "type": "DiscordEmbedFooter",
          "json": "footer",
          "help": "Footer information."
        },
        {
          "name": "Image",
          "type": "DiscordEmbedImage",
          "json": "image",
          "help": "Image information."
        },
        {
          "name": "Thumbnail",
          "type": "DiscordEmbedThumbnail",
          "json": "thumbnail",
          "help": "Thumbnail information."
        },
        {
          "name": "Author",
          "type": "DiscordEmbedAuthor",
          "json": "author",
          "help": "Author information."
        },
        {
          "name": "Fields",
          "type": "List<DiscordEmbedField>",
          "json": "fields",
          "help": "Fields information."
        }
      ]
    },
    {
      "name": "DiscordEmbedFooter",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Text",
          "type": "string",
          "json": "text",
          "help": "Footer text."
        },
        {
          "name": "IconUrl",
          "type": "string",
          "json": "icon_url",
          "help": "Url of footer icon (only supports http(s) and attachments)."
        }
      ]
    },
    {
      "name": "DiscordEmbedImage",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Url",
          "type": "string",
          "json": "url",
          "help": "Source url of image (only supports http(s) and attachments)."
        },
        {
          "name": "Height",
          "type": "int",
          "json": "height",
          "help": "Height of image."
        },
        {
          "name": "Width",
          "type": "int",
          "json": "width",
          "help": "Width of image."
        }
      ]
    },
    {
      "name": "DiscordEmbedThumbnail",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Url",
          "type": "string",
          "json": "url",
          "help": "Source url of thumbnail (only supports http(s) and attachments)."
        },
        {
          "name": "Height",
          "type": "int",
          "json": "height",
          "help": "Height of thumbnail."
        },
        {
          "name": "Width",
          "type": "int",
          "json": "width",
          "help": "Width of thumbnail."
        }
      ]
    },
    {
      "name": "DiscordEmbedAuthor",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Name",
          "type": "string",
          "json": "name",
          "help": "Name of author."
        },
        {
          "name": "Url",
          "type": "string",
          "json": "url",
          "help": "Url of author."
        },
        {
          "name": "IconUrl",
          "type": "string",
          "json": "icon_url",
          "help": "Url of author icon (only supports http(s) and attachments)."
        }
      ]
    },
    {
      "name": "DiscordEmbedField",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Name",
          "type": "string",
          "json": "name",
          "help": "Name of the field."
        },
        {
          "name": "Value",
          "type": "string",
          "json": "value",
          "help": "Value of the field."
        },
        {
          "name": "Inline",
          "type": "bool",
          "json": "inline",
          "help": "Whether or not this field should siplay inline."
        }
      ]
    }
  ],
  "enumerations": [
    {
      "name": "DiscordEmbedType",
      "values": [
        "rich",
        "image",
        "video",
        "gifv",
        "article",
        "link"
      ]
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/VSTest/VSTest.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/master/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://msdn.microsoft.com/en-us/library/jj155796.aspx#//div[@class='content']"
  ],
  "name": "VSTest",
  "officialUrl": "https://msdn.microsoft.com/en-us/library/jj155796.aspx",
  "help": "VSTest.Console.exe is the command-line command that is used to run tests. You can specify several options in any order on the VSTest.Console.exe command line.",
  "nugetPackageId": "Microsoft.TestPlatform",
  "packageExecutable": "vstest.console.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "TestAssemblies",
            "type": "List<string>",
            "format": "{value}",
            "position": 1,
            "help": "Run tests from the specified files. Separate multiple test file names with spaces."
          },
          {
            "name": "SettingsFile",
            "type": "string",
            "format": "/Settings:{value}",
            "help": "Run tests with additional settings such as data collectors."
          },
          {
            "name": "Tests",
            "type": "List<string>",
            "format": "/Tests:{value}",
            "separator": ",",
            "help": "Run tests with names that match the provided values. To provide multiple values, separate them by commas."
          },
          {
            "name": "Parallel",
            "type": "bool",
            "format": "/Parallel",
            "help": "Specifies that the tests be executed in parallel. By default up to all available cores on the machine may be used. The number of cores to use can be configured by using a settings file."
          },
          {
            "name": "EnableCodeCoverage",
            "type": "bool",
            "format": "/EnableCodeCoverage",
            "help": "Enables data diagnostic adapter CodeCoverage in the test run."
          },
          {
            "name": "InIsolation",
            "type": "bool",
            "format": "/InIsolation",
            "help": "Runs the tests in an isolated process."
          },
          {
            "name": "UseVsixExtensions",
            "type": "bool",
            "format": "/UseVsixExtensions:{value}",
            "help": "This makes vstest.console.exe process use or skip the VSIX extensions installed (if any) in the test run."
          },
          {
            "name": "TestAdapterPath",
            "type": "string",
            "format": "/TestAdapterPath:{value}",
            "help": "Forces the vstest.console.exe process to use custom test adapters from a specified path (if any) in the test run."
          },
          {
            "name": "Platform",
            "type": "VsTestPlatform",
            "format": "/Platform:{value}",
            "help": "Target platform architecture to be used for test execution."
          },
          {
            "name": "Framework",
            "type": "VsTestFramework",
            "format": "/Framework:{value}",
            "help": "Target .NET Framework version to be used for test execution."
          },
          {
            "name": "TestCaseFilters",
            "type": "List<string>",
            "format": "/TestCaseFilter:{value}",
            "separator": "|",
            "help": "Run tests that match the given expression.<para/><c>&lt;Expression&gt;</c> is of the format <c>&lt;property&gt;=&lt;value&gt;[|&lt;Expression&gt;]</c>.<para/>The <c>/TestCaseFilter</c> command line option cannot be used with the <c>/Tests</c> command line option.<para/>For information about creating and using expressions, see <a href=\"https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md\">TestCase filter</a>."
          },
          {
            "name": "Logger",
            "type": "string",
            "format": "/Logger:{value}",
            "help": "Specify a logger for test results. Example: To log results into a Visual Studio Test Results File (TRX) use <c>/Logger:trx</c>."
          },
          {
            "name": "ListTests",
            "type": "string",
            "format": "/ListTests:{value}",
            "help": "Lists discovered tests from the given test container."
          },
          {
            "name": "ListDiscoverers",
            "type": "bool",
            "format": "/ListDiscoverers",
            "help": "Lists installed test discoverers."
          },
          {
            "name": "ListExecutors",
            "type": "bool",
            "format": "/ListExecutors",
            "help": "Lists installed test executors."
          },
          {
            "name": "ListLoggers",
            "type": "bool",
            "format": "/ListLoggers",
            "help": "Lists installed test loggers."
          },
          {
            "name": "ListSettingsProviders",
            "type": "bool",
            "format": "/ListSettingsProviders",
            "help": "Lists installed test settings providers."
          },
          {
            "name": "DiagnosticsFile",
            "type": "string",
            "format": "/Diag:{value}",
            "help": "Writes diagnostic trace logs to the specified file."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "VsTestPlatform",
      "values": [
        "x86",
        "x64",
        "ARM"
      ]
    },
    {
      "name": "VsTestFramework",
      "values": [
        "Framework35",
        "Framework40",
        "Framework45"
      ]
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/Teams/Teams.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/main/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#office-365-connector-card",
    "https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook"
  ],
  "name": "Teams",
  "officialUrl": "https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software",
  "help": "Microsoft Teams is a proprietary business communication platform developed by Microsoft, as part of the Microsoft 365 family of products. Teams offers workspace chat and videoconferencing, file storage, and application integration. Teams is replacing other Microsoft-operated business messaging and collaboration platforms, including Skype for Business and Microsoft Classroom.",
  "dataClasses": [
    {
      "name": "TeamsMessage",
      "extensionMethods": true,
      "properties": [
        {
          "name": "Title",
          "type": "string",
          "json": "title"
        },
        {
          "name": "Text",
          "type": "string",
          "json": "text"
        },
        {
          "name": "ThemeColor",
          "type": "string",
          "json": "themeColor"
        }
      ]
    }
  ]
}
