=== KoiRealm/Fuke/source/Fuke.Tooling.Generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/KoiRealm/Fuke/main/source/Fuke.Tooling.Generator/schema.json",
  "title": "Tool specification schema file by FUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Enumeration is marked as obsolete when specified.",
          "type": "string"
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "json": {
          "description": "Name used when serializing to JSON.",
          "type": "string"
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "hidesBaseMember": {
          "description": "Specifies that the property hides an inherited member and requires the new modifier.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. Property is marked as obsolete when specified.",
          "type": "string"
        },
        "onlyDelegates": {
          "type": "boolean"
        },
        "isTailArgument": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "extensionMethods": {
          "description": "Enables generation of extension methods for modification.",
          "type": "boolean"
        },
        "omitDataClass": {
          "description": "Omits generation of the data class.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        "deprecationMessage": {
          "description": "Obsolete message. DataClass is marked as obsolete when specified.",
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "commonPropertySets": {
          "description": "Appends the properties of the named property sets.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preProcess": {
          "description": "Generates a pre-process hook",
          "type": "boolean"
        },
        "postProcess": {
          "description": "Generates a post-process hook",
          "type": "boolean"
        },
        "logLevelParsing": {
          "description": "Enables log level parsing",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "officialUrl": {
          "description": "Url of the task. If not specified, the tool url will be used.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        },
        "deprecationMessage": {
          "description": "Obsolete message. Task is marked as obsolete when specified.",
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[0-9A-Z][A-Za-z0-9]*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "deprecationMessage": {
      "description": "Obsolete message. Tool is marked as obsolete when specified.",
      "type": "string"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "nugetPackageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "npmPackageId": {
      "description": "ID for the NPM package.",
      "type": "string"
    },
    "aptgetPackageId": {
      "description": "ID for the AptGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "customLogger": {
      "description": "Enables custom logger.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "commonTaskPropertySets": {
      "description": "Named common property sets which can be used by tasks.",
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    },
    "_metadata": {
      "description": "Can be used to store additional information about the tool.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      }
    }
  },
  "required": [
    "name",
    "officialUrl"
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/Boots/Boots.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/master/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://github.com/jonathanpeppers/boots#systemcommandline"
  ],
  "name": "Boots",
  "officialUrl": "https://github.com/jonathanpeppers/boots",
  "help": "boots is a .NET global tool for <c>bootstrapping</c> <c>vsix</c> and <c>pkg</c> files.",
  "nugetPackageId": "Boots",
  "packageExecutable": "Boots.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "Stable",
            "type": "BootsProductType",
            "format": "--stable {value}",
            "help": "Install the latest <em>stable</em> version of a product from VS manifests. Options include: <c>Xamarin.Android</c>, <c>Xamarin.iOS</c>, <c>Xamarin.Mac</c>, and <c>Mono</c>"
          },
          {
            "name": "Preview",
            "type": "BootsProductType",
            "format": "--preview {value}",
            "help": "Install the latest <em>preview</em> version of a product from VS manifests. Options include: <c>Xamarin.Android</c>, <c>Xamarin.iOS</c>, <c>Xamarin.Mac</c>, and <c>Mono</c>"
          },
          {
            "name": "Url",
            "type": "string",
            "format": "--url {value}",
            "help": "A Url to a <c>pkg</c> or <c>vsix</c> file to install"
          },
          {
            "name": "FileType",
            "type": "BootsFileType",
            "format": "--file-type {value}",
            "help": "Specifies the type of file to be installed such as <c>vsix</c>, <c>pkg</c>, or <c>msi</c>. Defaults to <c>vsix</c> on Windows and <c>pkg</c> on macOS"
          },
          {
            "name": "Timeout",
            "type": "int",
            "format": "--timeout {value}",
            "help": "Specifies a timeout for <c>HttpClient</c>. If omitted, uses the .NET default of 100 seconds"
          },
          {
            "name": "ReadWriteTimeout",
            "type": "int",
            "format": "--read-write-timeout {value}",
            "help": "Specifies a timeout for reading/writing from a <c>HttpClient</c> stream. If omitted, uses a default of 300 seconds"
          },
          {
            "name": "Retries",
            "type": "int",
            "format": "--retries {value}",
            "help": "Specifies a number of retries for <c>HttpClient</c> failures. If omitted, uses a default of 3 retries"
          },
          {
            "name": "Version",
            "type": "bool",
            "format": "--version",
            "help": "Show version information"
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "BootsProductType",
      "values": [
        "Mono",
        "Xamarin.Android",
        "Xamarin.iOS",
        "Xamarin.Mac"
      ]
    },
    {
      "name": "BootsFileType",
      "values": [
        "vsix",
        "pkg",
        "msi"
      ]
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/MauiCheck/MauiCheck.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/master/source/Fuke.Tooling.Generator/schema.json",
  "name": "MauiCheck",
  "officialUrl": "https://github.com/Redth/dotnet-maui-check",
  "help": "A dotnet tool for helping set up your .NET MAUI environment.",
  "nugetPackageId": "Redth.Net.Maui.Check",
  "packageExecutable": "MauiCheck.dll",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "Manifest",
            "type": "string",
            "format": "--manifest {value}",
            "help": "Manifest files are currently used by the doctor to fetch the latest versions and requirements. The manifest is hosted by default at: <a href=\"https://aka.ms/dotnet-maui-check-manifest\">https://aka.ms/dotnet-maui-check-manifest</a>. Use this option to specify an alternative file path or URL to use."
          },
          {
            "name": "Fix",
            "type": "bool",
            "format": "--fix",
            "help": "You can try using the <c>--fix</c> argument to automatically enable solutions to run without being prompted."
          },
          {
            "name": "NonInteractive",
            "type": "bool",
            "format": "--non-interactive",
            "help": "If you're running on CI you may want to run without any required input with the <c>--non-interactive</c> argument. You can combine this with <c>--fix</c> to automatically fix without prompting."
          },
          {
            "name": "Preview",
            "type": "bool",
            "format": "--preview",
            "help": "This uses a more frequently updated manifest with newer versions of things more often. The manifest is hosted by default at: <a href=\"https://aka.ms/dotnet-maui-check-manifest-dev\">https://aka.ms/dotnet-maui-check-manifest-dev</a>"
          },
          {
            "name": "Ci",
            "type": "bool",
            "format": "--ci",
            "help": "Uses the <c>dotnet-install</c> powershell / bash scripts for installing the dotnet SDK version from the manifest instead of the global installer."
          },
          {
            "name": "Skip",
            "type": "List<MauiCheckCheckup>",
            "format": "--skip {value}",
            "help": "Skips a checkup by name or id as listed in maui-check list. NOTE: If there are any other checkups which depend on a skipped checkup, they will be skipped too."
          }
        ]
      }
    },
    {
      "postfix": "Config",
      "definiteArgument": "config",
      "settingsClass": {
        "properties": [
          {
            "name": "DotNetVersion",
            "type": "bool",
            "format": "--dotnet-version",
            "help": "Use the SDK version in the manifest in <em>global.json</em>."
          },
          {
            "name": "DotNetPrerelease",
            "type": "bool",
            "format": "--dotnet-pre {value}",
            "help": "Change the <c>allowPrerelease</c> value in the <em>global.json</em>."
          },
          {
            "name": "DotNetRollForward",
            "type": "MauiCheckDotNetRollForward",
            "format": "--dotnet-rollForward {value}",
            "help": "Change the <c>rollForward</c> value in <em>global.json</em> to one of the allowed values specified."
          },
          {
            "name": "NuGetSources",
            "type": "bool",
            "format": "--nuget-sources",
            "help": "Adds the nuget sources specified in the manifest to the <em>NuGet.config</em> and creates the file if needed."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "MauiCheckDotNetRollForward",
      "values": [
        "disable",
        "major",
        "minor",
        "feature",
        "patch",
        "latestMajor",
        "latestMinor",
        "latestFeature",
        "latestPatch"
      ]
    },
    {
      "name": "MauiCheckCheckup",
      "values": [
        "OpenJdkCheckup",
        "VisualStudioMacCheckup",
        "AndroidSdkPackagesCheckup",
        "AndroidEmulatorCheckup",
        "XCodeCheckup",
        "DotNetCheckup",
        "DotNetWorkloadDuplicatesCheckup",
        "DotNetSentinelCheckup",
        "DotNetWorkloadsCheckup"
      ]
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/ILRepack/ILRepack.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/master/source/Fuke.Tooling.Generator/schema.json",
  "name": "ILRepack",
  "officialUrl": "https://github.com/gluck/il-repack#readme",
  "help": "ILRepack is meant at replacing <a href=\"https://github.com/dotnet/ILMerge\">ILMerge</a> / <a href=\"https://evain.net/blog/articles/2006/11/06/an-introduction-to-mono-merge\">Mono.Merge</a>.<para/>The former being closed-source (<a href=\"https://github.com/Microsoft/ILMerge\">now open-sourced</a>), impossible to customize, slow, resource consuming and many more. The later being deprecated, unsupported, and based on an old version of Mono.Cecil.<para/>Here we're using latest (slightly modified) Cecil sources (0.9), you can find the fork <a href=\"https://github.com/gluck/cecil\">here</a>. Mono.Posix is also required (build only, it gets merged afterwards) for executable bit set on target file.",
  "nugetPackageId": "ILRepack",
  "packageExecutable": "ILRepack.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "KeyFile",
            "type": "string",
            "format": "--keyfile:{value}",
            "secret": false,
            "help": "Specifies a keyfile to sign the output assembly."
          },
          {
            "name": "KeyContainer",
            "type": "string",
            "format": "--keycontainer:{value}",
            "secret": false,
            "help": "Specifies a key container to sign the output assembly (takes precedence over <c>--keyfile</c>)."
          },
          {
            "name": "LogFile",
            "type": "string",
            "format": "--log:{value}",
            "help": "Enable logging (to a file, if given) (default is disabled)."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--ver:{value}",
            "help": "Target assembly version."
          },
          {
            "name": "Union",
            "type": "bool",
            "format": "--union",
            "help": "Merges types with identical names into one."
          },
          {
            "name": "NoDebug",
            "type": "bool",
            "format": "--ndebug",
            "help": "Disables symbol file generation."
          },
          {
            "name": "CopyAttributes",
            "type": "bool",
            "format": "--copyattrs",
            "help": "Copy assembly attributes (by default only the primary assembly attributes are copied)."
          },
          {
            "name": "Attr",
            "type": "string",
            "format": "--attr:{value}",
            "help": "Take assembly attributes from the given assembly file."
          },
          {
            "name": "AllowMultiple",
            "type": "bool",
            "format": "--allowMultiple",
            "help": "When <c>--copyattrs</c> is specified, allows multiple attributes (if type allows)."
          },
          {
            "name": "Target",
            "type": "ILRepackTarget",
            "format": "--target:{value}",
            "help": "Specify target assembly kind (<c>library</c>, <c>exe</c>, <c>winexe</c> supported, default is same as first assembly)."
          },
          {
            "name": "TargetPlatform",
            "type": "string",
            "format": "--targetplatform:{value}",
            "help": "Specify target platform (v1, v1.1, v2, v4 supported)."
          },
          {
            "name": "Xmldocs",
            "type": "bool",
            "format": "--xmldocs",
            "help": "Merges XML documentation as well."
          },
          {
            "name": "Lib",
            "type": "string",
            "format": "--lib:{value}",
            "help": "Adds the path to the search directories for referenced assemblies (can be specified multiple times)."
          },
          {
            "name": "Internalize",
            "type": "bool",
            "format": "--internalize",
            "help": "Sets all types but the ones from the first assembly <c>internal</c>."
          },
          {
            "name": "InternalizeExcludeFile",
            "type": "string",
            "format": "--internalize:{value}",
            "help": "Exclude file contains one regex per line to compare against fullname of types NOT to internalize."
          },
          {
            "name": "RenameInternalized",
            "type": "bool",
            "format": "--renameInternalized",
            "help": "Rename all internalized types."
          },
          {
            "name": "DelaySign",
            "type": "bool",
            "format": "--delaysign",
            "help": "Sets the key, but don't sign the assembly."
          },
          {
            "name": "AllowDuplicate",
            "type": "List<string>",
            "format": "--allowdup:{value}",
            "help": "Allows the specified type for being duplicated in input assemblies."
          },
          {
            "name": "AllowDuplicateResources",
            "type": "bool",
            "format": "--allowduplicateresources",
            "help": "Allows to duplicate resources in output assembly (by default they're ignored)."
          },
          {
            "name": "ZeroPekind",
            "type": "bool",
            "format": "--zeropekind",
            "help": "Allows assemblies with Zero <c>PeKind</c> (but obviously only IL will get merged)."
          },
          {
            "name": "Wildcards",
            "type": "bool",
            "format": "--wildcards",
            "help": "Allows (and resolves) file wildcards (e.g. <c>*.dll</c>) in input assemblies."
          },
          {
            "name": "Parallel",
            "type": "bool",
            "format": "--parallel",
            "help": "Use as many CPUs as possible to merge the assemblies."
          },
          {
            "name": "Pause",
            "type": "bool",
            "format": "--pause",
            "help": "Pause execution once completed (good for debugging)."
          },
          {
            "name": "RepackDrop",
            "type": "bool",
            "format": "--repackdrop:AttributeClass",
            "help": "Allows dropping specific members during merging (<a href=\"https://github.com/gluck/il-repack/issues/215\">#215</a>)."
          },
          {
            "name": "Verbose",
            "type": "bool",
            "format": "--verbose",
            "help": "Shows more logs."
          },
          {
            "name": "Output",
            "type": "string",
            "format": "--out:{value}",
            "help": "Target assembly path, <c>symbol/config/doc</c> files will be written here as well."
          },
          {
            "name": "Assemblies",
            "type": "List<string>",
            "format": "{value}",
            "position": -1,
            "help": "Primary and other assemblies to be merged."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "ILRepackTarget",
      "values": [
        "library",
        "exe",
        "winexe"
      ]
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/Fixie/Fixie.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/master/source/Fuke.Tooling.Generator/schema.json",
  "references": [
    "https://raw.githubusercontent.com/fixie/fixie/main/src/Fixie.Console/Program.cs"
  ],
  "name": "Fixie",
  "officialUrl": "https://fixie.github.io/",
  "help": "Fixie is a .NET modern test framework similar to NUnit and xUnit, but with an emphasis on low-ceremony defaults and flexible customization.",
  "nugetPackageId": "fixie.console",
  "packageExecutable": "dotnet-fixie.dll",
  "tasks": [
    {
      "help": "The <c>dotnet fixie</c> command is used to execute Fixie unit tests in a given project.",
      "settingsClass": {
        "properties": [
          {
            "name": "Configuration",
            "type": "string",
            "format": "--configuration {value}",
            "help": "The configuration under which to build. When this option is omitted, the default configuration is `Debug`."
          },
          {
            "name": "NoBuild",
            "type": "bool",
            "format": "--no-build",
            "help": "Skip building the test project prior to running it."
          },
          {
            "name": "Framework",
            "type": "string",
            "format": "--framework {value}",
            "help": "Only run test assemblies targeting a specific framework."
          },
          {
            "name": "Report",
            "type": "string",
            "format": "--report {value}",
            "help": "Write test results to the specified path, using the xUnit XML format."
          },
          {
            "name": "CustomArguments",
            "type": "string",
            "format": "-- {value}",
            "help": "Arbitrary arguments made available to custom discovery/execution classes."
          }
        ]
      }
    }
  ]
}

=== KoiRealm/Fuke/source/Fuke.Common/Tools/Git/Git.json
{
  "$schema": "https://raw.githubusercontent.com/KoiRealm/Fuke/main/source/Fuke.Tooling.Generator/schema.json",
  "name": "Git",
  "officialUrl": "https://git-scm.com/",
  "help": "Git is a <a href=\"https://git-scm.com/about/free-and-open-source\">free and open source</a> distributed version control system designed to handle everything from small to very large projects with speed and efficiency. Git is <a href=\"https://git-scm.com/documentation\">easy to learn</a> and has a <a href=\"https://git-scm.com/about/small-and-fast\">tiny footprint with lightning fast performance</a>. It outclasses SCM tools like Subversion, CVS, Perforce, and ClearCase with features like <a href=\"https://git-scm.com/about/branching-and-merging\">cheap local branching</a>, convenient <a href=\"https://git-scm.com/about/staging-area\">staging areas</a>, and <a href=\"https://git-scm.com/about/distributed\">multiple workflows</a>.",
  "pathExecutable": "git"
}
